### ISSUE TITLE
 Segmentation mapping file doesn't show in viewer after being selected

### ISSUE THREAD

**Issue by mkrunic** [AndrewRadev/protein-runway#50]
I am able to successfully load the trajectory and segmentation file and see the resulting protein movement, but the window itself doesn't actually show the segmentation file that was selected (but it does for the selected pdb file).

![image](https://github.com/user-attachments/assets/dd9536f5-54b1-4380-9289-465b8025a574)

**Comment by AndrewRadev** [comment]
The reason is likely because of the custom setter given by `set=` in this code: https://github.com/AndrewRadev/protein-runway/blob/bbd2f7840d8e612c0c956e442e45c67eccd5e7c1/blender/extension/__init__.py/#L26-L42

There might be a way to set the actual value in the same property, or maybe have a separate property that holds the "real" value and add a getter that reads it.

**Comment by AndrewRadev** [comment]
Fixed in https://github.com/AndrewRadev/protein-runway/commit/25348b6a3106424839580c78090f23e9c74afb39
